@startuml
set separator none
title Logger

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("EventManagementMicroApplication.EventManagementMicroApplication_boundary", "EventManagementMicroApplication", $tags="") {
  Component(EventManagementMicroApplication.EventManagementMicroApplication.Core, "Core", $techn="Module", $descr="", $tags="", $link="")
  Component(EventManagementMicroApplication.EventManagementMicroApplication.Logger, "Logger", $techn="Module", $descr="", $tags="", $link="")
}

Rel(EventManagementMicroApplication.EventManagementMicroApplication.Logger, EventManagementMicroApplication.EventManagementMicroApplication.Core, "listens to", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml