@startuml
set separator none
title User

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("EventManagementMicroApplication.EventManagementMicroApplication_boundary", "EventManagementMicroApplication", $tags="") {
  Component(EventManagementMicroApplication.EventManagementMicroApplication.Core, "Core", $techn="Module", $descr="", $tags="", $link="")
  Component(EventManagementMicroApplication.EventManagementMicroApplication.User, "User", $techn="Module", $descr="", $tags="", $link="")
}

Rel(EventManagementMicroApplication.EventManagementMicroApplication.User, EventManagementMicroApplication.EventManagementMicroApplication.Core, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml